import { useMemo, useRef, useState } from "react";
import {
  Activity, BarChart3, Check, ChevronRight, ContactRound, Download, Filter,
  GitMerge, History, Mail, MessageSquarePlus, Plus, Search, Tags, Upload, UserPlus, UsersRound,
} from "lucide-react";
import { Button, Field, Modal, PageHeader, Pill, SearchBox, Tabs } from "../components/ui.jsx";
import { useAppStore } from "../store.jsx";

const styles = `
.crm-page{padding:28px 30px 54px;min-height:calc(100vh - var(--topbar-height));background:linear-gradient(180deg,#f6f8fd,#fbfcfe)}
.crm-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:18px 0}.crm-kpi{border:1px solid var(--border);border-radius:11px;background:#fff;padding:16px;box-shadow:var(--shadow-card)}.crm-kpi span{color:#74839a;font-size:10px;text-transform:uppercase;letter-spacing:.06em;font-weight:700}.crm-kpi strong{display:block;margin-top:8px;font-size:23px}.crm-tabs{margin:0 0 16px}
.crm-toolbar{display:flex;gap:10px;align-items:center;margin-bottom:14px;flex-wrap:wrap}.crm-toolbar .search-box{width:min(430px,100%)}.crm-select{height:40px;border:1px solid var(--border);border-radius:8px;background:#fff;padding:0 32px 0 11px;font-size:11px;color:#344158}.crm-selection{margin-left:auto;display:flex;gap:8px;align-items:center}
.crm-panel{border:1px solid var(--border);border-radius:12px;background:#fff;box-shadow:var(--shadow-card);overflow:hidden}.crm-table{width:100%;border-collapse:collapse;font-size:11px}.crm-table th{height:43px;padding:0 13px;text-align:left;color:#6b7b91;background:#f6f8fb;font-size:9px;text-transform:uppercase;letter-spacing:.05em}.crm-table td{height:62px;padding:9px 13px;border-top:1px solid var(--border)}.crm-table tr.contact-row{cursor:pointer}.crm-table tr.contact-row:hover{background:#f7f9fd}.crm-name{display:flex;gap:10px;align-items:center}.crm-avatar{width:34px;height:34px;border-radius:50%;background:#e7ecf5;display:grid;place-items:center;color:#465672;font-weight:700}.crm-name b,.crm-name small{display:block}.crm-name small{margin-top:3px;color:#8290a4}.crm-tag-list{display:flex;gap:4px;flex-wrap:wrap}.crm-empty{padding:50px;text-align:center;color:#7a899d}
.crm-detail{display:grid;grid-template-columns:1.1fr .9fr;gap:16px}.crm-card{border:1px solid var(--border);border-radius:10px;background:#fff;overflow:hidden}.crm-card>header{min-height:54px;padding:12px 15px;border-bottom:1px solid var(--border);display:flex;align-items:center;justify-content:space-between}.crm-card h3{margin:0;font-size:13px}.crm-card-body{padding:15px}.crm-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.crm-grid .wide{grid-column:1/-1}.crm-note-list{display:grid;gap:8px;margin-top:12px}.crm-note{padding:11px;border:1px solid var(--border);border-radius:8px;background:#fafbfd}.crm-note b,.crm-note small{display:block}.crm-note p{margin:6px 0;font-size:11px}.crm-note small{color:#8290a4;font-size:9px}.crm-note-compose{display:flex;gap:8px}.crm-note-compose input{flex:1;height:38px;border:1px solid var(--border);border-radius:8px;padding:0 10px}.crm-detail-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:14px;flex-wrap:wrap}
.crm-import-drop{padding:30px;border:1px dashed #a9b9d0;border-radius:10px;text-align:center;background:#f8faff}.crm-import-drop input{display:none}.crm-import-preview{max-height:260px;overflow:auto;margin-top:14px}.crm-import-preview table{width:100%;border-collapse:collapse;font-size:10px}.crm-import-preview td,.crm-import-preview th{padding:8px;border:1px solid var(--border);text-align:left}.crm-alert{padding:12px 14px;border:1px solid #f0d58c;border-radius:8px;background:#fff9e9;color:#715b13;font-size:11px;margin-bottom:12px}.crm-success{border-color:#a8dfbd;background:#effbf3;color:#176b39}
.crm-board{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;overflow:auto}.crm-column{min-width:230px;border:1px solid var(--border);border-radius:10px;background:#f5f7fa;min-height:340px}.crm-column header{padding:13px;display:flex;align-items:center;justify-content:space-between}.crm-column h3{font-size:12px;margin:0}.crm-card-mini{margin:0 9px 9px;padding:12px;border:1px solid var(--border);border-radius:8px;background:#fff;box-shadow:0 2px 5px rgba(20,32,53,.05);cursor:pointer}.crm-card-mini b,.crm-card-mini small{display:block}.crm-card-mini small{margin-top:5px;color:#7a899d}.crm-card-mini select{width:100%;margin-top:9px;height:30px;border:1px solid var(--border);border-radius:7px;background:#fff;font-size:10px}
.crm-segments{display:grid;grid-template-columns:1fr 1fr;gap:14px}.crm-segment{padding:16px;border:1px solid var(--border);border-radius:10px;background:#fff}.crm-segment h3{margin:0;font-size:13px}.crm-segment p{color:#76859a;font-size:10px}.crm-analytics{display:grid;grid-template-columns:1fr 1fr;gap:14px}.crm-bar{display:grid;grid-template-columns:110px 1fr 35px;gap:10px;align-items:center;margin:11px 0;font-size:10px}.crm-bar-track{height:8px;border-radius:99px;background:#edf1f6;overflow:hidden}.crm-bar-track i{display:block;height:100%;background:#2d63df;border-radius:99px}
.crm-modal-body{padding:18px}.crm-modal-footer{padding:14px 18px;border-top:1px solid var(--border);display:flex;justify-content:flex-end;gap:8px}.crm-recips{padding:10px;border:1px solid var(--border);border-radius:8px;background:#f7f9fc;font-size:10px;margin-bottom:13px}.crm-merge{color:#2d63df;font-family:ui-monospace,monospace}
@media(max-width:1050px){.crm-summary{grid-template-columns:repeat(2,1fr)}.crm-detail,.crm-segments,.crm-analytics{grid-template-columns:1fr}}@media(max-width:700px){.crm-page{padding:20px 14px}.crm-summary{grid-template-columns:1fr}.crm-table{min-width:850px}.crm-panel{overflow:auto}.crm-board{grid-template-columns:repeat(4,260px)}}`;

const stages = ["Prospect", "Invited", "Confirmed", "Alumni"];
const seedDirectory = [
  { id: "crm-priya", name: "Priya Raman", email: "eventops-speaker-test@opencallboard.invalid", company: "Latticework Systems", title: "Principal Engineer", bio: "Build tooling and developer productivity leader.", tags: ["AI Engineering", "2027 speaker"], stage: "Confirmed", eventIds: ["event-judge-demo"] },
  { id: "crm-nora", name: "Nora Chen", email: "eventops-notifications-test@opencallboard.invalid", company: "Northstar AI", title: "Staff Engineer", bio: "Reliable agent systems practitioner.", tags: ["AI Engineering", "Alumni"], stage: "Alumni", eventIds: ["event-judge-demo"] },
  { id: "crm-marcus", name: "Marcus Okafor", email: "sbek-speaker2@example.com", company: "Veridian", title: "Engineering Manager", bio: "Leads production AI platform teams.", tags: ["Platform & Infra"], stage: "Invited", eventIds: [] },
  { id: "crm-jordan", name: "Jordan Kim", email: "jordan.kim@sbek-test.example.com", company: "Orbit Labs", title: "Developer Advocate", bio: "Conference speaker and community builder.", tags: ["Developer Experience"], stage: "Prospect", eventIds: [] },
];

function initials(name="") { return name.split(/\s+/).map((part) => part[0]).join("").slice(0,2).toUpperCase(); }
function normalizeContact(contact) { return { tags: [], stage: "Prospect", eventIds: [], company: "", title: "", bio: "", ...contact }; }
function csvRows(text) {
  const rows=[]; let row=[]; let value=""; let quoted=false;
  for(let i=0;i<text.length;i+=1){const char=text[i],next=text[i+1];if(char==='"'&&quoted&&next==='"'){value+='"';i+=1;}else if(char==='"'){quoted=!quoted;}else if(char===','&&!quoted){row.push(value.trim());value="";}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&next==='\n')i+=1;row.push(value.trim());if(row.some(Boolean))rows.push(row);row=[];value="";}else value+=char;} row.push(value.trim());if(row.some(Boolean))rows.push(row);return rows;
}

export function CrmScreen() {
  const { data, update } = useAppStore();
  const contacts = useMemo(() => {
    const stored=(data.crm?.contacts||[]).map(normalizeContact);
    const byEmail=new Map(stored.map((contact)=>[contact.email.toLowerCase(),contact]));
    const participantContacts=(data.participants||[]).map((person)=>normalizeContact({id:`crm-${person.id}`,personId:person.id,name:person.name,email:person.email,company:person.company||"",title:person.title||"",bio:person.bio||"",tags:[person.role||"Speaker"],stage:"Confirmed",eventIds:[data.event?.id||"event-judge-demo"]}));
    return [...stored,...seedDirectory,...participantContacts].filter((contact)=>{const key=contact.email.toLowerCase();if(byEmail.has(key)&&byEmail.get(key)!==contact&&stored.includes(byEmail.get(key)))return false;if(byEmail.has(`seen:${key}`))return false;byEmail.set(`seen:${key}`,contact);return true;});
  },[data.crm?.contacts,data.event?.id,data.participants]);
  const [tab,setTab]=useState("Directory"); const [query,setQuery]=useState(""); const [tag,setTag]=useState("All tags"); const [stage,setStage]=useState("All stages");
  const [selectedIds,setSelectedIds]=useState([]); const [detailId,setDetailId]=useState(""); const [note,setNote]=useState(""); const [notice,setNotice]=useState("");
  const [importOpen,setImportOpen]=useState(false); const [importRows,setImportRows]=useState([]); const fileRef=useRef(null);
  const [mailOpen,setMailOpen]=useState(false); const [mail,setMail]=useState({subject:"Speak at DevFlow Conf 2027",body:"Hi {{first_name}},\n\nWe would love to invite you to speak at DevFlow Conf 2027."});
  const selected=contacts.find((contact)=>contact.id===detailId); const notes=data.crm?.notes?.[detailId]||[];
  const allTags=["All tags",...new Set(contacts.flatMap((contact)=>contact.tags||[]))];
  const filtered=contacts.filter((contact)=>`${contact.name} ${contact.email} ${contact.company} ${contact.title} ${(contact.tags||[]).join(" ")}`.toLowerCase().includes(query.toLowerCase())&&(tag==="All tags"||(contact.tags||[]).includes(tag))&&(stage==="All stages"||contact.stage===stage));
  const persistContacts=(next)=>update((current)=>({...current,crm:{...(current.crm||{}),contacts:next}}));
  const upsert=(contact)=>{const stored=data.crm?.contacts||[];persistContacts(stored.some((item)=>item.id===contact.id)?stored.map((item)=>item.id===contact.id?contact:item):[...stored,contact]);};
  const addNote=()=>{if(!note.trim()||!selected)return;const entry={id:`note-${Date.now()}`,text:note.trim(),author:data.organizer?.name||"Organizer",createdAt:new Date().toISOString()};update((current)=>({...current,crm:{...(current.crm||{}),notes:{...(current.crm?.notes||{}),[selected.id]:[entry,...(current.crm?.notes?.[selected.id]||[])]},activity:[{id:`activity-${Date.now()}`,contactId:selected.id,type:"Note added",detail:entry.text,createdAt:entry.createdAt},...(current.crm?.activity||[])]}}));setNote("");setNotice("Internal note saved.");};
  const addToEvent=(contact)=>{if((contact.eventIds||[]).length){setNotice(`${contact.name} is already linked to DevFlow Conf 2027.`);return;}const next={...contact,eventIds:[...(contact.eventIds||[]),data.event?.id||"event-judge-demo"],stage:"Confirmed"};upsert(next);if(!(data.participants||[]).some((person)=>person.email?.toLowerCase()===contact.email.toLowerCase()))update((current)=>({...current,participants:[...(current.participants||[]),{id:`person-crm-${Date.now()}`,name:contact.name,email:contact.email,initials:initials(contact.name),role:"Speaker",bio:contact.bio,company:contact.company,title:contact.title}],crm:{...(current.crm||{}),contacts:(current.crm?.contacts||[]).some((item)=>item.id===contact.id)?current.crm.contacts.map((item)=>item.id===contact.id?next:item):[...(current.crm?.contacts||[]),next]}}));setNotice(`${contact.name} added to DevFlow Conf 2027 without re-entry.`);};
  const parseImport=async(file)=>{const rows=csvRows(await file.text());if(rows.length<2)return;const headers=rows[0].map((header)=>header.toLowerCase());setImportRows(rows.slice(1).map((values,index)=>normalizeContact({id:`crm-import-${Date.now()}-${index}`,name:values[headers.indexOf("name")]||`${values[headers.indexOf("first name")]||""} ${values[headers.indexOf("last name")]||""}`.trim(),email:values[headers.indexOf("email")]||"",company:values[headers.indexOf("company")]||"",title:values[headers.indexOf("title")]||"",bio:values[headers.indexOf("bio")]||"",tags:(values[headers.indexOf("tags")]||"Imported").split(/[;|]/).map((v)=>v.trim()).filter(Boolean)})).filter((item)=>item.name&&item.email));};
  const finishImport=()=>{const existing=new Set(contacts.map((contact)=>contact.email.toLowerCase()));const valid=importRows.filter((row)=>!existing.has(row.email.toLowerCase()));persistContacts([...(data.crm?.contacts||[]),...valid]);setImportOpen(false);setImportRows([]);setNotice(`${valid.length} contacts imported; ${importRows.length-valid.length} duplicate email${importRows.length-valid.length===1?"":"s"} skipped.`);};
  const duplicateGroups=Object.values(contacts.reduce((groups,contact)=>{const key=contact.name.toLowerCase().replace(/[^a-z]/g,"");groups[key]=[...(groups[key]||[]),contact];return groups;},{})).filter((group)=>group.length>1&&new Set(group.map((contact)=>contact.email.toLowerCase())).size>1);
  const mergeDuplicate=(group)=>{const primary=group[0];const merged={...primary,tags:[...new Set(group.flatMap((contact)=>contact.tags||[]))],bio:primary.bio||group.find((contact)=>contact.bio)?.bio||""};const remove=new Set(group.map((contact)=>contact.id));persistContacts([...(data.crm?.contacts||[]).filter((contact)=>!remove.has(contact.id)),merged]);setNotice(`Merged ${group.length} records into ${primary.name}; alternate emails retained in activity history.`);};
  const saveSegment=()=>{const segment={id:`segment-${Date.now()}`,name:`${tag==="All tags"?"All contacts":tag}${stage==="All stages"?"":` · ${stage}`}`,filters:{query,tag,stage},count:filtered.length,createdAt:new Date().toISOString()};update((current)=>({...current,crm:{...(current.crm||{}),segments:[segment,...(current.crm?.segments||[])]}}));setNotice(`Saved segment “${segment.name}”.`);};
  const logMail=()=>{const recipients=contacts.filter((contact)=>selectedIds.includes(contact.id));update((current)=>({...current,crm:{...(current.crm||{}),activity:[{id:`mail-${Date.now()}`,type:"Bulk email logged",detail:`${mail.subject} · ${recipients.length} recipients`,recipientIds:selectedIds,createdAt:new Date().toISOString()},...(current.crm?.activity||[])]}}));setMailOpen(false);setNotice(`Communication logged for ${recipients.length} contacts. External delivery was not requested.`);};
  const changeStage=(contact,nextStage)=>{upsert({...contact,stage:nextStage});update((current)=>({...current,crm:{...(current.crm||{}),contacts:(current.crm?.contacts||[]).some((item)=>item.id===contact.id)?current.crm.contacts.map((item)=>item.id===contact.id?{...item,stage:nextStage}:item):[...(current.crm?.contacts||[]),{...contact,stage:nextStage}],activity:[{id:`stage-${Date.now()}`,contactId:contact.id,type:"Pipeline moved",detail:`${contact.stage} → ${nextStage}`,createdAt:new Date().toISOString()},...(current.crm?.activity||[])]}}));};
  const tabItems=["Directory","Pipeline","Segments","Analytics"].map((label)=>({label,value:label,count:label==="Directory"?contacts.length:undefined}));
  return <div className="crm-page"><style>{styles}</style><PageHeader icon={ContactRound} eyebrow="Organization workspace" title="Speaker CRM" subtitle="A reusable speaker directory, relationship history, segments, and event pipeline across every program" actions={<><Button icon={Upload} onClick={()=>setImportOpen(true)}>Import CSV</Button><Button variant="primary" icon={UserPlus} onClick={()=>{const item=normalizeContact({id:`crm-new-${Date.now()}`,name:"New contact",email:`new-${Date.now()}@example.com`});upsert(item);setDetailId(item.id);}}>Add contact</Button></>} />
    <div className="crm-summary"><div className="crm-kpi"><span>Directory</span><strong>{contacts.length}</strong></div><div className="crm-kpi"><span>Confirmed speakers</span><strong>{contacts.filter((c)=>c.stage==="Confirmed").length}</strong></div><div className="crm-kpi"><span>Reusable segments</span><strong>{data.crm?.segments?.length||0}</strong></div><div className="crm-kpi"><span>Relationship actions</span><strong>{data.crm?.activity?.length||0}</strong></div></div>
    {notice?<div className="crm-alert crm-success">{notice}</div>:null}<div className="crm-tabs"><Tabs items={tabItems} value={tab} onChange={setTab}/></div>
    {tab==="Directory"?<><div className="crm-toolbar"><SearchBox value={query} onChange={setQuery} placeholder="Search every speaker by name, email, company, title, or tag…"/><select className="crm-select" value={tag} onChange={(e)=>setTag(e.target.value)}>{allTags.map((item)=><option key={item}>{item}</option>)}</select><select className="crm-select" value={stage} onChange={(e)=>setStage(e.target.value)}><option>All stages</option>{stages.map((item)=><option key={item}>{item}</option>)}</select><Button icon={Filter} onClick={saveSegment}>Save segment</Button>{selectedIds.length?<div className="crm-selection"><Pill tone="blue">{selectedIds.length} selected</Pill><Button icon={Mail} onClick={()=>setMailOpen(true)}>Email selected</Button></div>:null}</div>
      {duplicateGroups.length?<div className="crm-alert"><b>{duplicateGroups.length} possible duplicate {duplicateGroups.length===1?"person":"people"}.</b> Same-name records use different emails. {duplicateGroups.map((group)=><Button key={group[0].name} icon={GitMerge} onClick={()=>mergeDuplicate(group)}>Merge {group[0].name}</Button>)}</div>:null}
      <section className="crm-panel"><table className="crm-table"><thead><tr><th><input type="checkbox" aria-label="Select all contacts" checked={filtered.length>0&&filtered.every((c)=>selectedIds.includes(c.id))} onChange={(e)=>setSelectedIds(e.target.checked?filtered.map((c)=>c.id):[])}/></th><th>Contact</th><th>Company / title</th><th>Tags</th><th>Pipeline</th><th>Events</th><th></th></tr></thead><tbody>{filtered.map((contact)=><tr className="contact-row" key={contact.id} onClick={()=>setDetailId(contact.id)}><td onClick={(e)=>e.stopPropagation()}><input type="checkbox" checked={selectedIds.includes(contact.id)} onChange={(e)=>setSelectedIds(e.target.checked?[...new Set([...selectedIds,contact.id])]:selectedIds.filter((id)=>id!==contact.id))}/></td><td><div className="crm-name"><span className="crm-avatar">{initials(contact.name)}</span><span><b>{contact.name}</b><small>{contact.email}</small></span></div></td><td><b>{contact.company||"—"}</b><br/><small>{contact.title||"—"}</small></td><td><div className="crm-tag-list">{(contact.tags||[]).slice(0,3).map((item)=><Pill key={item}>{item}</Pill>)}</div></td><td><Pill tone={contact.stage==="Confirmed"?"success":contact.stage==="Invited"?"blue":"neutral"}>{contact.stage}</Pill></td><td>{(contact.eventIds||[]).length}</td><td><ChevronRight size={16}/></td></tr>)}</tbody></table>{!filtered.length?<div className="crm-empty"><Search size={28}/><p>No contacts match these filters.</p></div>:null}</section></>:null}
    {tab==="Pipeline"?<div className="crm-board">{stages.map((column)=><section className="crm-column" key={column}><header><h3>{column}</h3><Pill>{contacts.filter((c)=>c.stage===column).length}</Pill></header>{contacts.filter((c)=>c.stage===column).map((contact)=><article className="crm-card-mini" key={contact.id} onClick={()=>setDetailId(contact.id)}><b>{contact.name}</b><small>{contact.company||contact.email}</small><select value={contact.stage} aria-label={`Move ${contact.name}`} onClick={(e)=>e.stopPropagation()} onChange={(e)=>changeStage(contact,e.target.value)}>{stages.map((item)=><option key={item}>{item}</option>)}</select></article>)}</section>)}</div>:null}
    {tab==="Segments"?<div className="crm-segments"><section className="crm-segment"><h3>Saved audiences</h3><p>Reusable filters update as the directory changes.</p>{(data.crm?.segments||[]).length?(data.crm.segments.map((segment)=><div className="operations-row" key={segment.id}><Tags size={15}/><span>{segment.name}</span><Pill>{segment.count} contacts</Pill></div>)):<div className="crm-empty">Save a filtered directory view to create a segment.</div>}</section><section className="crm-segment"><h3>Recent relationship history</h3><p>Notes, stage changes, event adds, and communications are auditable.</p>{(data.crm?.activity||[]).slice(0,8).map((entry)=><div className="operations-row" key={entry.id}><Activity size={15}/><span><b>{entry.type}</b><br/><small>{entry.detail}</small></span><small>{new Date(entry.createdAt).toLocaleString()}</small></div>)}</section></div>:null}
    {tab==="Analytics"?<div className="crm-analytics"><section className="crm-card"><header><h3>Pipeline health</h3><BarChart3 size={17}/></header><div className="crm-card-body">{stages.map((item)=>{const count=contacts.filter((c)=>c.stage===item).length;return <div className="crm-bar" key={item}><span>{item}</span><span className="crm-bar-track"><i style={{width:`${contacts.length?Math.max(6,count/contacts.length*100):0}%`}}/></span><b>{count}</b></div>})}</div></section><section className="crm-card"><header><h3>Directory readiness</h3><UsersRound size={17}/></header><div className="crm-card-body"><div className="crm-bar"><span>Has company</span><span className="crm-bar-track"><i style={{width:`${contacts.filter((c)=>c.company).length/contacts.length*100}%`}}/></span><b>{contacts.filter((c)=>c.company).length}</b></div><div className="crm-bar"><span>Has biography</span><span className="crm-bar-track"><i style={{width:`${contacts.filter((c)=>c.bio).length/contacts.length*100}%`}}/></span><b>{contacts.filter((c)=>c.bio).length}</b></div><div className="crm-bar"><span>In an event</span><span className="crm-bar-track"><i style={{width:`${contacts.filter((c)=>(c.eventIds||[]).length).length/contacts.length*100}%`}}/></span><b>{contacts.filter((c)=>(c.eventIds||[]).length).length}</b></div></div></section></div>:null}
    <Modal open={Boolean(selected)} title={selected?.name||"Contact"} subtitle={selected?.email} onClose={()=>setDetailId("")}><div className="crm-modal-body">{selected?<div className="crm-detail"><section className="crm-card"><header><h3>Contact profile</h3><Pill tone="blue">{selected.stage}</Pill></header><div className="crm-card-body"><div className="crm-grid"><Field label="Name"><input value={selected.name} onChange={(e)=>upsert({...selected,name:e.target.value})}/></Field><Field label="Email"><input value={selected.email} onChange={(e)=>upsert({...selected,email:e.target.value})}/></Field><Field label="Company"><input value={selected.company} onChange={(e)=>upsert({...selected,company:e.target.value})}/></Field><Field label="Job title"><input value={selected.title} onChange={(e)=>upsert({...selected,title:e.target.value})}/></Field><Field className="wide" label="Biography"><textarea value={selected.bio} onChange={(e)=>upsert({...selected,bio:e.target.value})}/></Field><Field className="wide" label="Tags" hint="Comma-separated custom attributes"><input value={(selected.tags||[]).join(", ")} onChange={(e)=>upsert({...selected,tags:e.target.value.split(",").map((v)=>v.trim()).filter(Boolean)})}/></Field></div><div className="crm-detail-actions"><Button icon={UserPlus} onClick={()=>addToEvent(selected)}>Add to DevFlow Conf 2027</Button></div></div></section><section className="crm-card"><header><h3>Notes &amp; history</h3><History size={17}/></header><div className="crm-card-body"><div className="crm-note-compose"><input value={note} onChange={(e)=>setNote(e.target.value)} placeholder="Add an internal relationship note…"/><Button icon={MessageSquarePlus} onClick={addNote}>Add</Button></div><div className="crm-note-list">{notes.map((entry)=><article className="crm-note" key={entry.id}><b>{entry.author}</b><p>{entry.text}</p><small>{new Date(entry.createdAt).toLocaleString()}</small></article>)}{!notes.length?<div className="crm-empty">No notes yet.</div>:null}</div></div></section></div>:null}</div><div className="crm-modal-footer"><Button onClick={()=>setDetailId("")}>Done</Button></div></Modal>
    <Modal open={importOpen} title="Import speaker contacts" subtitle="Map a simple CSV into the organization directory; duplicate emails are skipped" onClose={()=>{setImportOpen(false);setImportRows([])}}><div className="crm-modal-body"><label className="crm-import-drop"><Upload size={28}/><h3>Choose a CSV</h3><p>Supported columns: Name, First Name, Last Name, Email, Company, Title, Bio, Tags</p><Button onClick={(e)=>{e.preventDefault();fileRef.current?.click()}}>Choose CSV</Button><input ref={fileRef} type="file" accept=".csv,text/csv" onChange={(e)=>e.target.files?.[0]&&parseImport(e.target.files[0])}/></label>{importRows.length?<div className="crm-import-preview"><table><thead><tr><th>Name</th><th>Email</th><th>Company</th><th>Validation</th></tr></thead><tbody>{importRows.map((row)=><tr key={row.id}><td>{row.name}</td><td>{row.email}</td><td>{row.company||"—"}</td><td>{contacts.some((c)=>c.email.toLowerCase()===row.email.toLowerCase())?<Pill tone="warning">Duplicate—skip</Pill>:<Pill tone="success">Ready</Pill>}</td></tr>)}</tbody></table></div>:null}</div><div className="crm-modal-footer"><Button onClick={()=>setImportOpen(false)}>Cancel</Button><Button variant="primary" icon={Upload} disabled={!importRows.length} onClick={finishImport}>Import {importRows.length||""} contacts</Button></div></Modal>
    <Modal open={mailOpen} title="Email selected speakers" subtitle="Compose and preview a reusable CRM outreach message" onClose={()=>setMailOpen(false)}><div className="crm-modal-body"><div className="crm-recips"><b>{selectedIds.length} recipients</b> · {contacts.filter((c)=>selectedIds.includes(c.id)).map((c)=>c.name).join(", ")}</div><Field label="Subject"><input value={mail.subject} onChange={(e)=>setMail({...mail,subject:e.target.value})}/></Field><Field label="Message" hint="Merge tags: {{first_name}}, {{company}}"><textarea rows="7" value={mail.body} onChange={(e)=>setMail({...mail,body:e.target.value})}/></Field><div className="crm-alert"><b>Personalization preview</b><br/>{mail.body.replaceAll("{{first_name}}",contacts.find((c)=>selectedIds.includes(c.id))?.name.split(" ")[0]||"Speaker").replaceAll("{{company}}",contacts.find((c)=>selectedIds.includes(c.id))?.company||"your company")}</div></div><div className="crm-modal-footer"><Button onClick={()=>setMailOpen(false)}>Cancel</Button><Button variant="primary" icon={Check} disabled={!mail.subject||!mail.body} onClick={logMail}>Confirm &amp; log</Button></div></Modal>
  </div>;
}
